language: python
python:
  - "3.5"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install python-cjson
# command to run tests, e.g. python setup.py test
script:  nosetests tests/
